### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by aarasawa** [aarasawa/agritag#1]

**Comment by aarasawa** [comment]
# Database

## What is it?
Database of pesticide applications in the state of California

## Where is it from?
California Department of Pesticide Regulation public databases

## What do you want to do with it?
Display these on a map of California, to show hotspots.

## To-Do
- [ ] Gather data from 2019
- [ ] Clean data from 2019
- [ ] Populate database with 2019 data
- [ ] Establish data pipeline for getting data into the database easier
- [ ] Incrementally add data from 2019 up to the latest data CDPR has
